import Head from 'next/head'
import CollapsableFilter from '../components/CollapsableFilter'
import EventCard from '../components/EventCard'
import Heading from '../components/Heading'
import styles from '../styles/Home.module.css'

const mockEvents = [
  {
    label: 'My birthday',
    date: new Date('2022-08-21'),
  },
  {
    label: 'Neryad stream',
    date: new Date('2022-05-06T12:03:34'),
  },
  {
    label: 'Fiesta en la playa',
    date: new Date('2022-05-06T12:03:34'),
  },
  {
    label: 'Aniversary',
    date: new Date('2022-10-10T12:06:21'),
  },
  {
    label: 'New year',
    date: new Date('2022-12-31'),
  },
]

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upcoming events</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Heading className={styles.title} title="Upcomming events!" />

        <aside className={styles.sidebar}>
          <CollapsableFilter label="Featured events" items={mockEvents} />

          <CollapsableFilter label="Last events added" items={mockEvents} />

          <CollapsableFilter label="Events by category" items={mockEvents} />

          <CollapsableFilter label="Events by location" items={mockEvents} />
        </aside>

        <div className={styles.events}>
          {[
            new Date('2022-05-08T15:00:53'),
            new Date('2022-05-06T12:03:34'),
            new Date('2022-08-21T12:05:15'),
            new Date('2022-12-31T12:27:24'),
            new Date('2022-10-10T12:06:21'),
            new Date('2022-11-06'),
          ]
            .sort((a, b) => a - b)
            .map((date, index) => (
              <EventCard key={index} date={date} />
            ))}
        </div>
      </main>
    </div>
  )
}
