import Head from 'next/head'
import EventCard from '../components/EventCard'
import Heading from '../components/Heading'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upcoming events</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Heading className={styles.title} title="Upcomming events!" />

        <aside className={styles.sidebar}>
          <div>Featured events</div>
          <div>Last events</div>
          <div>Other filters</div>
          <div>Other filters</div>
          <div>Other filters</div>
        </aside>

        <div className={styles.events}>
          {[
            new Date('2022-05-08T15:00:53'),
            new Date('2022-05-06T12:03:34'),
            new Date('2022-08-21T12:05:15'),
            new Date('2022-12-31T12:27:24'),
            new Date('2022-10-10T12:06:21'),
            new Date('2022-11-06'),
          ]
            .sort((a, b) => a - b)
            .map((date, index) => (
              <EventCard key={index} date={date} />
            ))}
        </div>
      </main>
    </div>
  )
}
