import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upcoming events</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className="mb-5 text-5xl font-bold">Upcomming events!</h1>

        <p className={styles.description}>Under construction!</p>
      </main>
    </div>
  )
}
