import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upcoming events</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-5xl font-bold mb-5">Upcomming events!</h1>

        <p className={styles.description}>In construction!</p>
      </main>
    </div>
  );
}
